<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dcmitype" nsURI="http://purl.org/dc/dcmitype/" nsPrefix="dcmitype">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&#xA;      DCMI Type Vocabulary XML Schema&#xA;      XML Schema for http://purl.org/dc/dcmitype/ namespace&#xA;&#xA;      Created 2008-02-11&#xA;&#xA;      Created by &#xA;&#xA;      Tim Cole (t-cole3@uiuc.edu)&#xA;      Tom Habing (thabing@uiuc.edu)&#xA;      Jane Hunter (jane@dstc.edu.au)&#xA;      Pete Johnston (p.johnston@ukoln.ac.uk),&#xA;      Carl Lagoze (lagoze@cs.cornell.edu)&#xA;&#xA;      This schema defines a simpleType which enumerates&#xA;      the allowable values for the DCMI Type Vocabulary.&#xA;    "/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="DCMIType" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DCMIType"/>
      <details key="memberTypes" value="DCMIType_._member_._0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DCMITypeMember0">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DCMIType_._member_._0"/>
    </eAnnotations>
    <eLiterals name="Collection"/>
    <eLiterals name="Dataset" value="1"/>
    <eLiterals name="Event" value="2"/>
    <eLiterals name="Image" value="3"/>
    <eLiterals name="MovingImage" value="4"/>
    <eLiterals name="StillImage" value="5"/>
    <eLiterals name="InteractiveResource" value="6"/>
    <eLiterals name="Service" value="7"/>
    <eLiterals name="Software" value="8"/>
    <eLiterals name="Sound" value="9"/>
    <eLiterals name="Text" value="10"/>
    <eLiterals name="PhysicalObject" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DCMITypeMember0Object" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DCMIType_._member_._0:Object"/>
      <details key="baseType" value="DCMIType_._member_._0"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
